In [1]:
from IPython.core.interactiveshell import InteractiveShell
import numpy as np
import pandas as pd
import seaborn as sns

InteractiveShell.ast_node_interactivity = "all"

In [2]:
%%time

! cd data; ls

plutos = {}
for boro in ['BK', 'BX', 'MN', 'QN', 'SI']:
    print(f'\n Loading {boro}...')
    plutos[boro] = pd.read_csv(f'pluto{boro}.csv', skiprows=None, nrows=None, low_memory=False)

print('\n Concatenating...')
pluto = pd.concat(list(plutos.values()), sort=False)
pluto = pluto.reset_index(drop=True)

print('\n Pickling... \n')
pluto.to_pickle('../pluto_full.pkl')

311.pkl        311b.csv       plutoBX.csv    plutoQN.csv    pluto_full.pkl
311a.csv       plutoBK.csv    plutoMN.csv    plutoSI.csv

 Loading BK...

 Loading BX...

 Loading MN...

 Loading QN...

 Loading SI...

 Concatenating...

 Pickling...
CPU times: user 20.4 s, sys: 4.19 s, total: 24.5 s
Wall time: 22.8 s

In [4]:
pd.set_option('max_columns', 9)
pd.set_option('max_colwidth', 10)
pd.set_option('max_rows', 1)
pluto

print()
pd.set_option('float_format', '{:.0f}'.format)
pd.set_option('max_rows', None)
pluto.describe().T

,Borough,Block,Lot,CD,...,PFIRM15_FLAG,Version,FIRM07_Flag,PFIRM15_Flag
0,BK,1,1,302,...,1,18V1,nan,nan

,count,mean,std,min,25%,50%,75%,max
Block,859212,5306,3697,0,2307,4808,7458,16350
Lot,859212,133,745,1,19,38,64,9978
CD,859212,354,101,101,306,402,412,595
CT2010,855138,462,377,1,170,351,662,9901
CB2010,838663,2056,1155,1,1004,2001,3000,9003
SchoolDist,856441,22,8,1,17,24,29,32
Council,856209,32,13,1,22,32,44,51
ZipCode,855058,11012,471,10001,10466,11221,11370,12345
PolicePrct,856260,87,29,1,66,102,111,123
HealthCenterDistrict,856554,38,10,11,33,41,45,51
HealthArea,855901,3267,2664,100,920,2710,4700,9300
SanitBoro,852867,3,1,1,3,4,4,8
SanitDistrict,852898,8,5,1,3,8,12,95
LandUse,856354,2,2,1,1,1,2,11
Easements,859212,0,0,0,0,0,0,28
LotArea,859212,7933,372492,0,2000,2515,4000,214755710
BldgArea,859212,6383,60162,0,1372,2000,3000,24000000
ComArea,859212,2114,50089,0,0,0,0,24000000
ResArea,859212,4039,30837,0,1194,1645,2400,13211398
OfficeArea,859212,760,21287,0,0,0,0,3583167
RetailArea,859212,322,5798,0,0,0,0,2192088
GarageArea,859212,142,5669,0,0,0,0,2677430
StrgeArea,859212,119,4766,0,0,0,0,1757298
FactryArea,859212,135,4227,0,0,0,0,1324592
OtherArea,859212,610,40596,0,0,0,0,24000000
AreaSource,859212,2,1,0,2,2,2,7
NumBldgs,859212,1,3,0,1,1,2,1850
NumFloors,859212,2,2,0,2,2,2,205
UnitsRes,859212,4,34,0,1,2,2,10914
UnitsTotal,859212,5,42,0,1,2,2,17369
LotFront,859212,40,75,0,20,25,40,9999
LotDepth,859212,104,69,0,97,100,100,9999
BldgFront,859212,26,34,0,18,20,25,8050
BldgDepth,859212,46,37,0,34,42,53,9388
ProxCode,858724,2,1,0,1,1,2,3
LotType,858724,5,1,0,5,5,5,9
BsmtCode,858724,2,1,0,1,2,2,5
AssessLand,859212,113824,5790490,0,6839,9638,14650,3211276050
AssessTot,859212,460412,11192110,0,23700,31227,48013,6957914603
ExemptLand,859212,51375,5709676,0,0,0,1470,3211276050
ExemptTot,859212,165509,10205460,0,0,0,1470,6957914603
YearBuilt,859212,1840,432,0,1920,1930,1955,2040
YearAlter1,859212,206,607,0,0,0,0,2017
YearAlter2,859212,33,254,0,0,0,0,2017
BuiltFAR,859212,1,8,0,0,1,1,5801
ResidFAR,859212,1,1,0,1,1,2,12
CommFAR,859212,0,1,0,0,0,0,15
FacilFAR,859212,2,2,0,1,2,2,15
BoroCode,859212,3,1,1,3,4,4,5
BBL,859212,3516025594,1031635823,1000010010,3031540145,4008560022,4106480016,5080500094
CondoNo,859212,15,187,0,0,0,0,9566
Tract2010,859212,9261,26280,0,207,484,1120,157903
XCoord,835256,1006248,32319,913123,989589,1008786,1029096,1067279
YCoord,835256,191559,30522,120308,168268,189230,210993,272275
TaxMap,857990,36702,10867,1,31101,40601,44701,53203
APPBBL,858724,394753302,1216698754,0,0,0,0,5080480068
PLUTOMapID,859212,1,0,1,1,1,1,5
FIRM07_FLAG,32621,1,0,1,1,1,1,1
PFIRM15_FLAG,62869,1,0,1,1,1,1,1
FIRM07_Flag,1941,1,0,1,1,1,1,1
PFIRM15_Flag,2749,1,0,1,1,1,1,1